project:
  type: website
  output-dir: docs

website:
  # header: capa.png
  margin-header: email.html
  title: "Nextech"
  site-url: http://dragaocaolho.me/
  description: "Um blog sobre tecnologia e cultura"
  navbar:
    left:
      - about.qmd
    right:
      - icon: github
        href: https://github.com/nextmarte
      - icon: linkedin
        href: https://www.linkedin.com/in/marcus-ramalho-8a440545/
      - icon: rss
        href: index.xml
      - icon: youtube
        href: https://www.youtube.com/channel/UCL1aCShE8iFsqfMqglIFNcw
format:
  html:
    theme: cyborg
      # dark: 
      # light: slate
    css: styles.css



